package com.enviro.assessment.grad001.zandisentiyane.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

// This entity class represents a WasteCategory, which stores details about waste categories in the system.
@Entity
public class WasteCategory {

    // Unique identifier for each WasteCategory, auto-generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Category name is required; it cannot be blank.
    @NotBlank(message = "Category name is mandatory")
    private String categoryName;

    // Guidelines for disposal of the waste, limited to a max of 500 characters.
    @Size(max = 500, message = "Disposal guidelines should not exceed 500 characters")
    private String disposalGuidelines;

    // Tips for recycling the waste, limited to a max of 500 characters.
    @Size(max = 500, message = "Recycling tips should not exceed 500 characters")
    private String recyclingTips;

    // Getters and Setters for the entity fields
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCategoryName() {
        return categoryName;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    public String getDisposalGuidelines() {
        return disposalGuidelines;
    }

    public void setDisposalGuidelines(String disposalGuidelines) {
        this.disposalGuidelines = disposalGuidelines;
    }

    public String getRecyclingTips() {
        return recyclingTips;
    }

    public void setRecyclingTips(String recyclingTips) {
        this.recyclingTips = recyclingTips;
    }
}